-- Migration script to add missing columns for tier-based drive assignment
-- This script adds columns that are referenced in the assignTierBasedDriveToUser function

-- Add missing columns to drive_configurations table
ALTER TABLE drive_configurations 
ADD COLUMN IF NOT EXISTS is_auto_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS associated_user_id INTEGER REFERENCES users(id);

-- Add missing columns to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS is_combo_only BOOLEAN DEFAULT FALSE;

-- Add comments for the new columns
COMMENT ON COLUMN drive_configurations.is_auto_generated IS 'Indicates if this configuration was auto-generated by the system';
COMMENT ON COLUMN drive_configurations.associated_user_id IS 'User ID for whom this configuration was specifically created (for auto-generated configs)';
COMMENT ON COLUMN products.is_combo_only IS 'Indicates if this product can only be used in combo orders';

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_drive_configurations_is_auto_generated ON drive_configurations(is_auto_generated);
CREATE INDEX IF NOT EXISTS idx_drive_configurations_associated_user_id ON drive_configurations(associated_user_id);
CREATE INDEX IF NOT EXISTS idx_products_is_combo_only ON products(is_combo_only);
